-- Generated by tools/generate.py; do not edit.
local pack = ForeverVO_DataPack
pack.gossip = {
	[3309] = {
		{ f="3309-2f8d506f", h="2f8d506f", t="Besides the Grunts outside, my brothers and I fought at the battle of Hyjal. Any who seek to steal from the bank must face us first.", d=9.680 },
		{ f="3309-6b36598f", h="6b36598f", t="I guarantee this bank's security with my own blood, is that good enough for you?", d=6.960 },
		{ f="3309-ae78a458", h="ae78a458", t="Would you rather trust your goods with a goblin?", d=3.640 },
	},
	[3318] = {
		{ f="3318-ae78a458", h="ae78a458", t="Would you rather trust your goods with a goblin?", d=3.920 },
	},
	[5943] = {
		{ f="5943-a28d29e1", h="a28d29e1", t="I can train you in First Aid techniques.", d=3.200 },
	},
	[6929] = {
		{ f="6929-7161de72", h="7161de72", t="If we are to make these new lands ours then we must have places to rest our battle weary bodies. Lay your axe by the fire and share the stories of your mighty battles.", d=15.800 },
	},
}
