-- Generated by tools/generate.py; do not edit.
local pack = ForeverVO_DataPack
pack.npcs = {
	[255] = "Gerard Tiller",
	[658] = "Sten Stoutarm",
	[3142] = "Orgnil Soulscar",
	[3143] = "Gornek",
	[3153] = "Frang",
	[3154] = "Jen'shan",
	[3155] = "Rwag",
	[3157] = "Shikrik",
	[3309] = "Karus",
	[3318] = "Koma",
	[3707] = "Ken'jai",
	[5884] = "Mai'ah",
	[5943] = "Rawrk",
	[6929] = "Innkeeper Gryshka",
}
