[pronunciations]
"Ahn'Qiraj" = "Awnkeraj"
Gnomeregan = "Nomer-gahn"
Kharanos = "Karranos"
"Quel'Thalas" = "Quell Thalas"
Sharptalon = "Sharp Talon"
Tirisfal = "Tirrisfal"
Varimathras = "Vairimathrus"
Feralas = "fairalass"
Lordaeron = "Lorderon"
"Eldre'Thalas" = "Eldra thelass"
Tyrande = "teronda"
naxxramas = "naxRAMuss"
Arthas = "Arthus"
Arathor = "Airathor"
Arathi = "Arathi"
Tauren = "Toren"
Thatsh = "That's"
Sho = "So"
exshellent = "excellent"
newsh = "news"
Goldshire = "Gold-shire"
Gnarlpines = "Gnarl Pines"
furbolgs = "fur ballgs"
"Ban'ethil" = "Ban'Ethyl"
Athridas = "Athridahs"
Gnarlpine = "Gnarl pine"
furbolg = "fur ballg"
Jaina = "jay'nuh"
"ya mon" = "yah mahn"
"Zul'Gurub" = "Zul'Gahrub"
draught = "droutt"
draughts = "droutts"
Malygos = "Mala'gos"
Maraudon = "Maraadon"
Zaetar = "Zaytar"
Desolace = "DeSOlace"
phial = "file"
Runetotem = "Rune totem"
Blazerunner = "Blaze Runner"
Irontree = "Iron Tree"
Defias = "duhfyus"
