# /// script
# requires-python = ">=3.11"
# dependencies = ["requests"]
# ///
"""Builds and (optionally) uploads voice pack releases.

Two packs are released from the one working folder (ForeverVO_Data holds
everything on the maintainer's machine):

  base   ForeverVO_Data          Classic-era lines (source: classic). Huge,
                                 rarely released.
  delta  ForeverVO_Data_Forever  lines captured in game, from the beta cache
                                 or from the community. Small, released often,
                                 higher priority so it overrides the base.

    ./tools/run.sh tools/release_pack.py delta               # build zip only
    ./tools/run.sh tools/release_pack.py delta --upload      # and upload to CurseForge
    ./tools/run.sh tools/release_pack.py delta --upload --if-changed   # nightly use
    ./tools/run.sh tools/release_pack.py base

Audio is re-encoded for release (mono 48 kbps mp3) into tools/data/release/.
Versions are date based (2026.09.21, then 2026.09.21.2 on the same day).

Upload needs ~/.config/forever-vo/curseforge.json:
    {"token": "<CurseForge API token>", "projects": {"delta": 1234567, "base": 1234568}}
(CF_API_KEY and FVO_CF_DELTA_PROJECT / FVO_CF_BASE_PROJECT in the environment override it.)
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import zipfile
from datetime import date
from pathlib import Path

import requests

from config import DATA_DIR, SOUND_INDEX, SOUNDS_DIR
from generate import load_items, load_sources, rebuild_tables, sound_folder

RELEASE_DIR = DATA_DIR / "release"
STATE_FILE = DATA_DIR / "release_state.json"
CF_API = "https://wow.curseforge.com/api"
GAME_VERSION_NAME = "1.60.1"

PACKS = {
    "base": {
        "folder": "ForeverVO_Data",
        "title": "Forever Voiceover Data",
        "pack_name": "Classic",
        "priority": 100,
        "notes": "Classic-era quests and gossip, voiced. Install with Forever Voiceover.",
        "select": lambda entry: entry.get("source", "classic") == "classic" and not entry.get("player"),
    },
    "delta": {
        "folder": "ForeverVO_Data_Forever",
        "title": "Forever Voiceover Data: Forever",
        "pack_name": "Forever",
        "priority": 200,
        "notes": "New and revised Forever lines from player captures. Sits on top of Forever Voiceover Data.",
        "select": lambda entry: entry.get("source", "classic") != "classic" or bool(entry.get("player")),
    },
}


def next_version(pack: str) -> str:
    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}
    today = date.today().strftime("%Y.%m.%d")
    last = state.get(pack, {}).get("version", "")
    if last.startswith(today):
        n = int(last.split(".")[4]) + 1 if last.count(".") == 4 else 2
        return f"{today}.{n}"
    return today


def transcode(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-i", str(src), "-ac", "1", "-ar", "22050",
         "-codec:a", "libmp3lame", "-b:a", "48k", str(dst)],
        check=True,
    )


def write_manifest(stage: Path, spec: dict, version: str) -> None:
    stage.mkdir(parents=True, exist_ok=True)
    folder = spec["folder"]
    pack_global = f"{folder}Pack"
    (stage / f"{folder}.toc").write_text(
        f"## Interface: 16001\n## Title: {spec['title']}\n## Notes: {spec['notes']}\n## Version: {version}\n"
        f"## Author: Quinn Dougherty\n## Dependencies: ForeverVO\n## X-ForeverVO-Pack: 1\n## X-Category: Quests & Leveling\n\n"
        f"Data\\Pack.lua\nData\\Quests.lua\nData\\Gossip.lua\nData\\NPCs.lua\nData\\Register.lua\n",
        encoding="utf-8",
    )
    data = stage / "Data"
    data.mkdir(parents=True, exist_ok=True)
    (data / "Pack.lua").write_text(
        f"-- Generated by tools/release_pack.py\n{pack_global} = {{\n    name = \"{spec['pack_name']}\",\n"
        f"    version = \"{version}\",\n    priority = {spec['priority']},\n    folder = \"{folder}\",\n"
        f"    quests = {{}},\n    gossip = {{}},\n    npcs = {{}},\n}}\n",
        encoding="utf-8",
    )
    (data / "Register.lua").write_text(
        f"if ForeverVO and ForeverVO.RegisterPack then\n    ForeverVO.RegisterPack({pack_global})\nend\n",
        encoding="utf-8",
    )


def build(pack: str, version: str) -> tuple[Path, dict]:
    spec = PACKS[pack]
    sources = load_sources()
    items = [item for item in load_items(sources, include_progress=True) if spec["select"](item.entry)]
    stage = RELEASE_DIR / spec["folder"]
    if stage.exists():
        shutil.rmtree(stage)
    write_manifest(stage, spec, version)

    sound_index = json.loads(SOUND_INDEX.read_text()) if SOUND_INDEX.exists() else {}
    # Tables first (against the working audio), then copy only the files they reference
    stats = rebuild_tables(items, sound_index, data_dir=stage / "Data", pack_global=f"{spec['folder']}Pack",
                           sounds_dir=SOUNDS_DIR, write_index=False)
    for base in sorted(stats["files"]):
        folder = sound_folder(base)
        transcode(SOUNDS_DIR / folder / f"{base}.mp3", stage / "Sounds" / folder / f"{base}.mp3")

    zip_path = RELEASE_DIR / f"{spec['folder']}-{version}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(stage.rglob("*")):
            if path.is_file():
                zf.write(path, str(Path(spec["folder"]) / path.relative_to(stage)))
    size_mb = zip_path.stat().st_size / 1e6
    print(f"{zip_path.name}: {stats['quests']} quests, {stats['gossip']} gossip lines, {len(stats['files'])} files, {size_mb:.0f} MB")
    return zip_path, stats


CONFIG_FILE = Path.home() / ".config" / "forever-vo" / "curseforge.json"


def curseforge_config(pack: str) -> tuple[str | None, int | None]:
    """(api token, project id) for the pack, from the environment or the config file."""
    conf = json.loads(CONFIG_FILE.read_text()) if CONFIG_FILE.exists() else {}
    key = os.environ.get("CF_API_KEY") or conf.get("token")
    project = os.environ.get(f"FVO_CF_{pack.upper()}_PROJECT") or (conf.get("projects") or {}).get(pack)
    return key, (int(project) if project else None)


def game_version_id(key: str) -> int:
    versions = requests.get(f"{CF_API}/game/versions", headers={"X-Api-Token": key}, timeout=60).json()
    for entry in versions:
        if entry.get("name") == GAME_VERSION_NAME:
            return int(entry["id"])
    raise SystemExit(f"CurseForge has no game version named {GAME_VERSION_NAME}")


def upload(pack: str, zip_path: Path, version: str, stats: dict, release_type: str) -> None:
    key, project = curseforge_config(pack)
    if not key or not project:
        raise SystemExit(f"upload needs a token and a project id for {pack} in {CONFIG_FILE}")
    changelog = (f"{version}: {stats['quests']} quests, {stats['gossip']} gossip lines, {len(stats['files'])} sound files.\n\n"
                 f"Generated from lines captured by players; see https://github.com/quinn-dougherty/forever-vo")
    metadata = {
        "changelog": changelog,
        "changelogType": "markdown",
        "displayName": f"{PACKS[pack]['title']} {version}",
        "gameVersions": [game_version_id(key)],
        "releaseType": release_type,
    }
    with zip_path.open("rb") as f:
        response = requests.post(
            f"{CF_API}/projects/{project}/upload-file",
            headers={"X-Api-Token": key},
            data={"metadata": json.dumps(metadata)},
            files={"file": (zip_path.name, f, "application/zip")},
            timeout=3600,
        )
    if response.status_code != 200:
        raise SystemExit(f"upload failed: HTTP {response.status_code} {response.text[:300]}")
    print(f"uploaded to CurseForge project {project} as file {response.json().get('id')}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("pack", choices=sorted(PACKS))
    parser.add_argument("--upload", action="store_true", help="upload to CurseForge after building")
    parser.add_argument("--if-changed", action="store_true", help="skip when the set of files is unchanged since the last release")
    parser.add_argument("--release-type", default="beta", choices=["alpha", "beta", "release"])
    args = parser.parse_args(argv)

    if args.upload:
        key, project = curseforge_config(args.pack)
        if not key or not project:
            print(f"CurseForge upload not configured for {args.pack} ({CONFIG_FILE}); skipping")
            return 0

    version = next_version(args.pack)
    zip_path, stats = build(args.pack, version)

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}
    fingerprint = sorted(stats["files"])
    if args.if_changed and state.get(args.pack, {}).get("files") == fingerprint:
        print("no new files since the last release; nothing to do")
        zip_path.unlink(missing_ok=True)
        return 0

    if args.upload:
        upload(args.pack, zip_path, version, stats, args.release_type)
    state[args.pack] = {"version": version, "files": fingerprint, "zip": str(zip_path)}
    STATE_FILE.write_text(json.dumps(state, indent=1), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
