local _, ns = ...

--[[
One-time welcome on first login explaining where the voices come from and how
to contribute lines. The "seen" flag is kept in an addon-registered CVar rather
than saved variables, because this beta client does not load saved variables
back, but it does persist the CVar store.
]]

local Welcome = {}
ns.Welcome = Welcome

local CVAR = "ForeverVO_welcomed"
local POPUP = "FOREVERVO_WELCOME"

local TEXT = table.concat({
    "|cff6ec6ffForever Voiceover|r reads quests and NPC dialogue aloud using voices generated by players, not by Blizzard.",
    "",
    "Quest text is not in the game files, so the voice pack can only cover lines someone has seen. Play with the addon on, and when a line has no voice yet, type |cffffd100/fvo export|r and paste the string on the pinned GitHub issue. A bot turns it into audio for everyone.",
    "",
    "Only the quest or gossip text, the speaking NPC and the zone are shared. Your character name is removed.",
}, "\n")

StaticPopupDialogs[POPUP] = {
    text = TEXT,
    button1 = "Got it",
    button2 = "Open options",
    OnCancel = function()
        ns.SettingsPanel:Open()
    end,
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
    wide = true,
    preferredIndex = 3,
}

local function HasSeen()
    return C_CVar.GetCVar(CVAR) == "1"
end

local function MarkSeen()
    C_CVar.SetCVar(CVAR, "1")
end

function Welcome:Show()
    StaticPopup_Show(POPUP)
    MarkSeen()
end

ns.OnInit(function()
    pcall(C_CVar.RegisterCVar, CVAR, "0")
end)

ns.OnLogin(function()
    if HasSeen() then
        return
    end
    C_Timer.After(4, function()
        Welcome:Show()
    end)
end)
