local _, ns = ...

--[[
One-time welcome on first login explaining where the voices come from and how
to contribute lines. The "seen" flag is kept in an addon-registered CVar rather
than saved variables, because this beta client does not load saved variables
back, but it does persist the CVar store.

The welcome is a frame of the addon's own, not a StaticPopup. With the client's
alpha gamepad UI on, every StaticPopup that opens is handed to the gamepad
frame manager, which ends in the protected SetPreferredGamepadInteractTarget;
a popup an addon opened taints that path, the call is blocked, and the
"blocked action" popup that reports it runs the same path again, freezing the
client (issue #44). The manager only watches StaticPopups, UI panels and menus,
so a plain frame shown directly never reaches it.
]]

local Welcome = {}
ns.Welcome = Welcome

local CVAR = "ForeverVO_welcomed"
local WIDTH = 420 -- the width of a wide StaticPopup
local PADDING = 16
local BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_GAP = 128, 22, 8

local TEXT = table.concat({
    "|cff6ec6ffForever Voiceover|r reads quests and NPC dialogue aloud using voices generated by players, not by Blizzard.",
    "",
    "|cffffd100Voice pack coming.|r This release collects the lines. Until a pack is installed you will hear nothing, and each unvoiced quest or NPC prints a reminder in chat.",
    "",
    "Quest text is not in the game files, so the voice pack can only cover lines someone has seen. Play with the addon on, and when a line has no voice yet, type |cffffd100/fvo export|r and paste the string on the pinned GitHub issue. A bot turns it into audio for everyone.",
    "",
    "Only the quest or gossip text, the speaking NPC and the zone are shared. Your character name is removed.",
}, "\n")

local function HasSeen()
    return C_CVar.GetCVar(CVAR) == "1"
end

local function MarkSeen()
    C_CVar.SetCVar(CVAR, "1")
end

function Welcome:GetFrame()
    if self.frame then
        return self.frame
    end
    local frame = CreateFrame("Frame", "ForeverVOWelcome", UIParent)
    self.frame = frame
    frame:SetWidth(WIDTH)
    frame:SetPoint("TOP", UIParent, "TOP", 0, -135) -- where StaticPopup1 sits
    frame:SetFrameStrata("DIALOG")
    frame:SetClampedToScreen(true)
    frame:EnableMouse(true)
    frame:Hide()
    tinsert(UISpecialFrames, "ForeverVOWelcome") -- close with Escape

    frame.Border = CreateFrame("Frame", nil, frame, "DialogBorderDarkTemplate")
    frame.Border:SetAllPoints()

    frame.Text = frame:CreateFontString(nil, "ARTWORK")
    frame.Text:SetFontObject("GameFontHighlight")
    frame.Text:SetJustifyH("CENTER")
    frame.Text:SetWidth(WIDTH - 2 * PADDING)
    frame.Text:SetPoint("TOP", 0, -PADDING)
    frame.Text:SetText(TEXT)

    local accept = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")
    accept:SetSize(BUTTON_WIDTH, BUTTON_HEIGHT)
    accept:SetPoint("TOPRIGHT", frame.Text, "BOTTOM", -BUTTON_GAP / 2, -PADDING)
    accept:SetText("Got it")
    accept:SetScript("OnClick", function()
        frame:Hide()
    end)
    frame.Accept = accept

    local options = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")
    options:SetSize(BUTTON_WIDTH, BUTTON_HEIGHT)
    options:SetPoint("TOPLEFT", frame.Text, "BOTTOM", BUTTON_GAP / 2, -PADDING)
    options:SetText("Open options")
    options:SetScript("OnClick", function()
        frame:Hide()
        ns.SettingsPanel:Open()
    end)
    frame.Options = options

    frame:SetHeight(PADDING + frame.Text:GetStringHeight() + PADDING + BUTTON_HEIGHT + PADDING)
    return frame
end

function Welcome:Show()
    self:GetFrame():Show()
    MarkSeen()
end

ns.OnInit(function()
    pcall(C_CVar.RegisterCVar, CVAR, "0")
end)

ns.OnLogin(function()
    if HasSeen() then
        return
    end
    C_Timer.After(4, function()
        Welcome:Show()
    end)
end)
